server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: fish

  profiles:
    active: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  security:
    access-token-expiration: 15m
    refresh-token-expiration: 30d
  cors:
    allowed-origins:
      - "http://localhost:8080"
      - "https://example.com"
